// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: WeatherData.proto
// Protobuf Java Version: 4.31.1

package org.example.data;

@com.google.protobuf.Generated
public final class WeatherDataOuterClass {
  private WeatherDataOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      WeatherDataOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface WeatherDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.example.data.WeatherData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string station_id = 1;</code>
     * @return The stationId.
     */
    java.lang.String getStationId();
    /**
     * <code>string station_id = 1;</code>
     * @return The bytes for stationId.
     */
    com.google.protobuf.ByteString
        getStationIdBytes();

    /**
     * <code>string city = 2;</code>
     * @return The city.
     */
    java.lang.String getCity();
    /**
     * <code>string city = 2;</code>
     * @return The bytes for city.
     */
    com.google.protobuf.ByteString
        getCityBytes();

    /**
     * <code>.org.example.data.WeatherData.WeatherDirection weather_direction = 3;</code>
     * @return The enum numeric value on the wire for weatherDirection.
     */
    int getWeatherDirectionValue();
    /**
     * <code>.org.example.data.WeatherData.WeatherDirection weather_direction = 3;</code>
     * @return The weatherDirection.
     */
    org.example.data.WeatherDataOuterClass.WeatherData.WeatherDirection getWeatherDirection();

    /**
     * <code>int32 temperature = 4;</code>
     * @return The temperature.
     */
    int getTemperature();

    /**
     * <code>double rainChance = 5;</code>
     * @return The rainChance.
     */
    double getRainChance();

    /**
     * <code>int32 windSpeed = 6;</code>
     * @return The windSpeed.
     */
    int getWindSpeed();

    /**
     * <code>int64 date = 7;</code>
     * @return The date.
     */
    long getDate();
  }
  /**
   * Protobuf type {@code org.example.data.WeatherData}
   */
  public static final class WeatherData extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:org.example.data.WeatherData)
      WeatherDataOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 31,
        /* patch= */ 1,
        /* suffix= */ "",
        WeatherData.class.getName());
    }
    // Use WeatherData.newBuilder() to construct.
    private WeatherData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private WeatherData() {
      stationId_ = "";
      city_ = "";
      weatherDirection_ = 0;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.example.data.WeatherDataOuterClass.internal_static_org_example_data_WeatherData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.example.data.WeatherDataOuterClass.internal_static_org_example_data_WeatherData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.example.data.WeatherDataOuterClass.WeatherData.class, org.example.data.WeatherDataOuterClass.WeatherData.Builder.class);
    }

    /**
     * Protobuf enum {@code org.example.data.WeatherData.WeatherDirection}
     */
    public enum WeatherDirection
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>N = 0;</code>
       */
      N(0),
      /**
       * <code>NE = 1;</code>
       */
      NE(1),
      /**
       * <code>E = 2;</code>
       */
      E(2),
      /**
       * <code>SE = 3;</code>
       */
      SE(3),
      /**
       * <code>S = 4;</code>
       */
      S(4),
      /**
       * <code>SW = 5;</code>
       */
      SW(5),
      /**
       * <code>W = 6;</code>
       */
      W(6),
      /**
       * <code>NW = 7;</code>
       */
      NW(7),
      UNRECOGNIZED(-1),
      ;

      static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
          com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
          /* major= */ 4,
          /* minor= */ 31,
          /* patch= */ 1,
          /* suffix= */ "",
          WeatherDirection.class.getName());
      }
      /**
       * <code>N = 0;</code>
       */
      public static final int N_VALUE = 0;
      /**
       * <code>NE = 1;</code>
       */
      public static final int NE_VALUE = 1;
      /**
       * <code>E = 2;</code>
       */
      public static final int E_VALUE = 2;
      /**
       * <code>SE = 3;</code>
       */
      public static final int SE_VALUE = 3;
      /**
       * <code>S = 4;</code>
       */
      public static final int S_VALUE = 4;
      /**
       * <code>SW = 5;</code>
       */
      public static final int SW_VALUE = 5;
      /**
       * <code>W = 6;</code>
       */
      public static final int W_VALUE = 6;
      /**
       * <code>NW = 7;</code>
       */
      public static final int NW_VALUE = 7;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static WeatherDirection valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static WeatherDirection forNumber(int value) {
        switch (value) {
          case 0: return N;
          case 1: return NE;
          case 2: return E;
          case 3: return SE;
          case 4: return S;
          case 5: return SW;
          case 6: return W;
          case 7: return NW;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<WeatherDirection>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          WeatherDirection> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<WeatherDirection>() {
              public WeatherDirection findValueByNumber(int number) {
                return WeatherDirection.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.example.data.WeatherDataOuterClass.WeatherData.getDescriptor().getEnumTypes().get(0);
      }

      private static final WeatherDirection[] VALUES = values();

      public static WeatherDirection valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private WeatherDirection(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:org.example.data.WeatherData.WeatherDirection)
    }

    public static final int STATION_ID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object stationId_ = "";
    /**
     * <code>string station_id = 1;</code>
     * @return The stationId.
     */
    @java.lang.Override
    public java.lang.String getStationId() {
      java.lang.Object ref = stationId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        stationId_ = s;
        return s;
      }
    }
    /**
     * <code>string station_id = 1;</code>
     * @return The bytes for stationId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStationIdBytes() {
      java.lang.Object ref = stationId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stationId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CITY_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object city_ = "";
    /**
     * <code>string city = 2;</code>
     * @return The city.
     */
    @java.lang.Override
    public java.lang.String getCity() {
      java.lang.Object ref = city_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        city_ = s;
        return s;
      }
    }
    /**
     * <code>string city = 2;</code>
     * @return The bytes for city.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCityBytes() {
      java.lang.Object ref = city_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        city_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int WEATHER_DIRECTION_FIELD_NUMBER = 3;
    private int weatherDirection_ = 0;
    /**
     * <code>.org.example.data.WeatherData.WeatherDirection weather_direction = 3;</code>
     * @return The enum numeric value on the wire for weatherDirection.
     */
    @java.lang.Override public int getWeatherDirectionValue() {
      return weatherDirection_;
    }
    /**
     * <code>.org.example.data.WeatherData.WeatherDirection weather_direction = 3;</code>
     * @return The weatherDirection.
     */
    @java.lang.Override public org.example.data.WeatherDataOuterClass.WeatherData.WeatherDirection getWeatherDirection() {
      org.example.data.WeatherDataOuterClass.WeatherData.WeatherDirection result = org.example.data.WeatherDataOuterClass.WeatherData.WeatherDirection.forNumber(weatherDirection_);
      return result == null ? org.example.data.WeatherDataOuterClass.WeatherData.WeatherDirection.UNRECOGNIZED : result;
    }

    public static final int TEMPERATURE_FIELD_NUMBER = 4;
    private int temperature_ = 0;
    /**
     * <code>int32 temperature = 4;</code>
     * @return The temperature.
     */
    @java.lang.Override
    public int getTemperature() {
      return temperature_;
    }

    public static final int RAINCHANCE_FIELD_NUMBER = 5;
    private double rainChance_ = 0D;
    /**
     * <code>double rainChance = 5;</code>
     * @return The rainChance.
     */
    @java.lang.Override
    public double getRainChance() {
      return rainChance_;
    }

    public static final int WINDSPEED_FIELD_NUMBER = 6;
    private int windSpeed_ = 0;
    /**
     * <code>int32 windSpeed = 6;</code>
     * @return The windSpeed.
     */
    @java.lang.Override
    public int getWindSpeed() {
      return windSpeed_;
    }

    public static final int DATE_FIELD_NUMBER = 7;
    private long date_ = 0L;
    /**
     * <code>int64 date = 7;</code>
     * @return The date.
     */
    @java.lang.Override
    public long getDate() {
      return date_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(stationId_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, stationId_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(city_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, city_);
      }
      if (weatherDirection_ != org.example.data.WeatherDataOuterClass.WeatherData.WeatherDirection.N.getNumber()) {
        output.writeEnum(3, weatherDirection_);
      }
      if (temperature_ != 0) {
        output.writeInt32(4, temperature_);
      }
      if (java.lang.Double.doubleToRawLongBits(rainChance_) != 0) {
        output.writeDouble(5, rainChance_);
      }
      if (windSpeed_ != 0) {
        output.writeInt32(6, windSpeed_);
      }
      if (date_ != 0L) {
        output.writeInt64(7, date_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(stationId_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, stationId_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(city_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, city_);
      }
      if (weatherDirection_ != org.example.data.WeatherDataOuterClass.WeatherData.WeatherDirection.N.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, weatherDirection_);
      }
      if (temperature_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, temperature_);
      }
      if (java.lang.Double.doubleToRawLongBits(rainChance_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, rainChance_);
      }
      if (windSpeed_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, windSpeed_);
      }
      if (date_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, date_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.example.data.WeatherDataOuterClass.WeatherData)) {
        return super.equals(obj);
      }
      org.example.data.WeatherDataOuterClass.WeatherData other = (org.example.data.WeatherDataOuterClass.WeatherData) obj;

      if (!getStationId()
          .equals(other.getStationId())) return false;
      if (!getCity()
          .equals(other.getCity())) return false;
      if (weatherDirection_ != other.weatherDirection_) return false;
      if (getTemperature()
          != other.getTemperature()) return false;
      if (java.lang.Double.doubleToLongBits(getRainChance())
          != java.lang.Double.doubleToLongBits(
              other.getRainChance())) return false;
      if (getWindSpeed()
          != other.getWindSpeed()) return false;
      if (getDate()
          != other.getDate()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @SuppressWarnings("unchecked")
    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STATION_ID_FIELD_NUMBER;
      hash = (53 * hash) + getStationId().hashCode();
      hash = (37 * hash) + CITY_FIELD_NUMBER;
      hash = (53 * hash) + getCity().hashCode();
      hash = (37 * hash) + WEATHER_DIRECTION_FIELD_NUMBER;
      hash = (53 * hash) + weatherDirection_;
      hash = (37 * hash) + TEMPERATURE_FIELD_NUMBER;
      hash = (53 * hash) + getTemperature();
      hash = (37 * hash) + RAINCHANCE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getRainChance()));
      hash = (37 * hash) + WINDSPEED_FIELD_NUMBER;
      hash = (53 * hash) + getWindSpeed();
      hash = (37 * hash) + DATE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getDate());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.example.data.WeatherDataOuterClass.WeatherData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.data.WeatherDataOuterClass.WeatherData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.data.WeatherDataOuterClass.WeatherData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.data.WeatherDataOuterClass.WeatherData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.data.WeatherDataOuterClass.WeatherData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.data.WeatherDataOuterClass.WeatherData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.data.WeatherDataOuterClass.WeatherData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.example.data.WeatherDataOuterClass.WeatherData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.example.data.WeatherDataOuterClass.WeatherData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.example.data.WeatherDataOuterClass.WeatherData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.example.data.WeatherDataOuterClass.WeatherData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.example.data.WeatherDataOuterClass.WeatherData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.example.data.WeatherDataOuterClass.WeatherData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.example.data.WeatherData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.example.data.WeatherData)
        org.example.data.WeatherDataOuterClass.WeatherDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.example.data.WeatherDataOuterClass.internal_static_org_example_data_WeatherData_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.example.data.WeatherDataOuterClass.internal_static_org_example_data_WeatherData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.example.data.WeatherDataOuterClass.WeatherData.class, org.example.data.WeatherDataOuterClass.WeatherData.Builder.class);
      }

      // Construct using org.example.data.WeatherDataOuterClass.WeatherData.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        stationId_ = "";
        city_ = "";
        weatherDirection_ = 0;
        temperature_ = 0;
        rainChance_ = 0D;
        windSpeed_ = 0;
        date_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.example.data.WeatherDataOuterClass.internal_static_org_example_data_WeatherData_descriptor;
      }

      @java.lang.Override
      public org.example.data.WeatherDataOuterClass.WeatherData getDefaultInstanceForType() {
        return org.example.data.WeatherDataOuterClass.WeatherData.getDefaultInstance();
      }

      @java.lang.Override
      public org.example.data.WeatherDataOuterClass.WeatherData build() {
        org.example.data.WeatherDataOuterClass.WeatherData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.example.data.WeatherDataOuterClass.WeatherData buildPartial() {
        org.example.data.WeatherDataOuterClass.WeatherData result = new org.example.data.WeatherDataOuterClass.WeatherData(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.example.data.WeatherDataOuterClass.WeatherData result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.stationId_ = stationId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.city_ = city_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.weatherDirection_ = weatherDirection_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.temperature_ = temperature_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.rainChance_ = rainChance_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.windSpeed_ = windSpeed_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.date_ = date_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.example.data.WeatherDataOuterClass.WeatherData) {
          return mergeFrom((org.example.data.WeatherDataOuterClass.WeatherData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.example.data.WeatherDataOuterClass.WeatherData other) {
        if (other == org.example.data.WeatherDataOuterClass.WeatherData.getDefaultInstance()) return this;
        if (!other.getStationId().isEmpty()) {
          stationId_ = other.stationId_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getCity().isEmpty()) {
          city_ = other.city_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.weatherDirection_ != 0) {
          setWeatherDirectionValue(other.getWeatherDirectionValue());
        }
        if (other.getTemperature() != 0) {
          setTemperature(other.getTemperature());
        }
        if (java.lang.Double.doubleToRawLongBits(other.getRainChance()) != 0) {
          setRainChance(other.getRainChance());
        }
        if (other.getWindSpeed() != 0) {
          setWindSpeed(other.getWindSpeed());
        }
        if (other.getDate() != 0L) {
          setDate(other.getDate());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                stationId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                city_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                weatherDirection_ = input.readEnum();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                temperature_ = input.readInt32();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 41: {
                rainChance_ = input.readDouble();
                bitField0_ |= 0x00000010;
                break;
              } // case 41
              case 48: {
                windSpeed_ = input.readInt32();
                bitField0_ |= 0x00000020;
                break;
              } // case 48
              case 56: {
                date_ = input.readInt64();
                bitField0_ |= 0x00000040;
                break;
              } // case 56
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object stationId_ = "";
      /**
       * <code>string station_id = 1;</code>
       * @return The stationId.
       */
      public java.lang.String getStationId() {
        java.lang.Object ref = stationId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          stationId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string station_id = 1;</code>
       * @return The bytes for stationId.
       */
      public com.google.protobuf.ByteString
          getStationIdBytes() {
        java.lang.Object ref = stationId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          stationId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string station_id = 1;</code>
       * @param value The stationId to set.
       * @return This builder for chaining.
       */
      public Builder setStationId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        stationId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string station_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearStationId() {
        stationId_ = getDefaultInstance().getStationId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string station_id = 1;</code>
       * @param value The bytes for stationId to set.
       * @return This builder for chaining.
       */
      public Builder setStationIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        stationId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object city_ = "";
      /**
       * <code>string city = 2;</code>
       * @return The city.
       */
      public java.lang.String getCity() {
        java.lang.Object ref = city_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          city_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string city = 2;</code>
       * @return The bytes for city.
       */
      public com.google.protobuf.ByteString
          getCityBytes() {
        java.lang.Object ref = city_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          city_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string city = 2;</code>
       * @param value The city to set.
       * @return This builder for chaining.
       */
      public Builder setCity(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        city_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string city = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCity() {
        city_ = getDefaultInstance().getCity();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string city = 2;</code>
       * @param value The bytes for city to set.
       * @return This builder for chaining.
       */
      public Builder setCityBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        city_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private int weatherDirection_ = 0;
      /**
       * <code>.org.example.data.WeatherData.WeatherDirection weather_direction = 3;</code>
       * @return The enum numeric value on the wire for weatherDirection.
       */
      @java.lang.Override public int getWeatherDirectionValue() {
        return weatherDirection_;
      }
      /**
       * <code>.org.example.data.WeatherData.WeatherDirection weather_direction = 3;</code>
       * @param value The enum numeric value on the wire for weatherDirection to set.
       * @return This builder for chaining.
       */
      public Builder setWeatherDirectionValue(int value) {
        weatherDirection_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.org.example.data.WeatherData.WeatherDirection weather_direction = 3;</code>
       * @return The weatherDirection.
       */
      @java.lang.Override
      public org.example.data.WeatherDataOuterClass.WeatherData.WeatherDirection getWeatherDirection() {
        org.example.data.WeatherDataOuterClass.WeatherData.WeatherDirection result = org.example.data.WeatherDataOuterClass.WeatherData.WeatherDirection.forNumber(weatherDirection_);
        return result == null ? org.example.data.WeatherDataOuterClass.WeatherData.WeatherDirection.UNRECOGNIZED : result;
      }
      /**
       * <code>.org.example.data.WeatherData.WeatherDirection weather_direction = 3;</code>
       * @param value The weatherDirection to set.
       * @return This builder for chaining.
       */
      public Builder setWeatherDirection(org.example.data.WeatherDataOuterClass.WeatherData.WeatherDirection value) {
        if (value == null) { throw new NullPointerException(); }
        bitField0_ |= 0x00000004;
        weatherDirection_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.org.example.data.WeatherData.WeatherDirection weather_direction = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearWeatherDirection() {
        bitField0_ = (bitField0_ & ~0x00000004);
        weatherDirection_ = 0;
        onChanged();
        return this;
      }

      private int temperature_ ;
      /**
       * <code>int32 temperature = 4;</code>
       * @return The temperature.
       */
      @java.lang.Override
      public int getTemperature() {
        return temperature_;
      }
      /**
       * <code>int32 temperature = 4;</code>
       * @param value The temperature to set.
       * @return This builder for chaining.
       */
      public Builder setTemperature(int value) {

        temperature_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>int32 temperature = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearTemperature() {
        bitField0_ = (bitField0_ & ~0x00000008);
        temperature_ = 0;
        onChanged();
        return this;
      }

      private double rainChance_ ;
      /**
       * <code>double rainChance = 5;</code>
       * @return The rainChance.
       */
      @java.lang.Override
      public double getRainChance() {
        return rainChance_;
      }
      /**
       * <code>double rainChance = 5;</code>
       * @param value The rainChance to set.
       * @return This builder for chaining.
       */
      public Builder setRainChance(double value) {

        rainChance_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>double rainChance = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearRainChance() {
        bitField0_ = (bitField0_ & ~0x00000010);
        rainChance_ = 0D;
        onChanged();
        return this;
      }

      private int windSpeed_ ;
      /**
       * <code>int32 windSpeed = 6;</code>
       * @return The windSpeed.
       */
      @java.lang.Override
      public int getWindSpeed() {
        return windSpeed_;
      }
      /**
       * <code>int32 windSpeed = 6;</code>
       * @param value The windSpeed to set.
       * @return This builder for chaining.
       */
      public Builder setWindSpeed(int value) {

        windSpeed_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>int32 windSpeed = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearWindSpeed() {
        bitField0_ = (bitField0_ & ~0x00000020);
        windSpeed_ = 0;
        onChanged();
        return this;
      }

      private long date_ ;
      /**
       * <code>int64 date = 7;</code>
       * @return The date.
       */
      @java.lang.Override
      public long getDate() {
        return date_;
      }
      /**
       * <code>int64 date = 7;</code>
       * @param value The date to set.
       * @return This builder for chaining.
       */
      public Builder setDate(long value) {

        date_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>int64 date = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearDate() {
        bitField0_ = (bitField0_ & ~0x00000040);
        date_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.example.data.WeatherData)
    }

    // @@protoc_insertion_point(class_scope:org.example.data.WeatherData)
    private static final org.example.data.WeatherDataOuterClass.WeatherData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.example.data.WeatherDataOuterClass.WeatherData();
    }

    public static org.example.data.WeatherDataOuterClass.WeatherData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<WeatherData>
        PARSER = new com.google.protobuf.AbstractParser<WeatherData>() {
      @java.lang.Override
      public WeatherData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<WeatherData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<WeatherData> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.example.data.WeatherDataOuterClass.WeatherData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_data_WeatherData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_example_data_WeatherData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021WeatherData.proto\022\020org.example.data\"\224\002" +
      "\n\013WeatherData\022\022\n\nstation_id\030\001 \001(\t\022\014\n\004cit" +
      "y\030\002 \001(\t\022I\n\021weather_direction\030\003 \001(\0162..org" +
      ".example.data.WeatherData.WeatherDirecti" +
      "on\022\023\n\013temperature\030\004 \001(\005\022\022\n\nrainChance\030\005 " +
      "\001(\001\022\021\n\twindSpeed\030\006 \001(\005\022\014\n\004date\030\007 \001(\003\"N\n\020" +
      "WeatherDirection\022\005\n\001N\020\000\022\006\n\002NE\020\001\022\005\n\001E\020\002\022\006" +
      "\n\002SE\020\003\022\005\n\001S\020\004\022\006\n\002SW\020\005\022\005\n\001W\020\006\022\006\n\002NW\020\007b\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_org_example_data_WeatherData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_example_data_WeatherData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_example_data_WeatherData_descriptor,
        new java.lang.String[] { "StationId", "City", "WeatherDirection", "Temperature", "RainChance", "WindSpeed", "Date", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
